ALTER DEFAULT PRIVILEGES IN SCHEMA search_svc REVOKE ALL ON SEQUENCES FROM search_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA search_svc REVOKE ALL ON TABLES FROM search_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA search_svc FROM search_role;
REVOKE ALL ON ALL TABLES IN SCHEMA search_svc FROM search_role;
REVOKE USAGE ON SCHEMA search_svc FROM search_role;
