apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: catalog
