apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app.kubernetes.io/name: shipping
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8092
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 50059
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: shipping
