apiVersion: v1
kind: Service
metadata:
  name: inquiry
  labels:
    app.kubernetes.io/name: inquiry
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8090
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: inquiry
