apiVersion: v1
kind: Service
metadata:
  name: search
  labels:
    app.kubernetes.io/name: search
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8085
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: search
