ALTER DEFAULT PRIVILEGES IN SCHEMA auth_svc REVOKE ALL ON SEQUENCES FROM auth_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth_svc REVOKE ALL ON TABLES FROM auth_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA auth_svc FROM auth_role;
REVOKE ALL ON ALL TABLES IN SCHEMA auth_svc FROM auth_role;
REVOKE USAGE ON SCHEMA auth_svc FROM auth_role;
