apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8084
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: inventory
