ALTER DEFAULT PRIVILEGES IN SCHEMA catalog_svc REVOKE ALL ON SEQUENCES FROM catalog_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog_svc REVOKE ALL ON TABLES FROM catalog_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA catalog_svc FROM catalog_role;
REVOKE ALL ON ALL TABLES IN SCHEMA catalog_svc FROM catalog_role;
REVOKE USAGE ON SCHEMA catalog_svc FROM catalog_role;
