ALTER DEFAULT PRIVILEGES IN SCHEMA inquiry_svc REVOKE ALL ON SEQUENCES FROM inquiry_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA inquiry_svc REVOKE ALL ON TABLES FROM inquiry_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA inquiry_svc FROM inquiry_role;
REVOKE ALL ON ALL TABLES IN SCHEMA inquiry_svc FROM inquiry_role;
REVOKE USAGE ON SCHEMA inquiry_svc FROM inquiry_role;
