-- Historical migration.
--
-- The original up-script created auth_svc.subscription_plans +
-- auth_svc.seller_subscriptions and seeded plans. 002 relocated those
-- tables to subscription_svc and dropped the auth_svc originals.
--
-- After Phase 3 (subscription split to its own Postgres instance), a
-- fresh subscription-only DB has no auth_svc schema, so the original
-- CREATE TABLE auth_svc.* statements would fail. Shared-cluster DBs have
-- this version recorded in schema_migrations_subscription already, so
-- changing the body here has no effect on them — golang-migrate skips
-- applied versions regardless of content.
--
-- All the useful work is redone in 002 idempotently, so this file is a
-- no-op on fresh DBs.
SELECT 1;
