ALTER DEFAULT PRIVILEGES IN SCHEMA loyalty_svc REVOKE ALL ON SEQUENCES FROM loyalty_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA loyalty_svc REVOKE ALL ON TABLES FROM loyalty_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA loyalty_svc FROM loyalty_role;
REVOKE ALL ON ALL TABLES IN SCHEMA loyalty_svc FROM loyalty_role;
REVOKE USAGE ON SCHEMA loyalty_svc FROM loyalty_role;
