ALTER DEFAULT PRIVILEGES IN SCHEMA order_svc REVOKE ALL ON SEQUENCES FROM order_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA order_svc REVOKE ALL ON TABLES FROM order_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA order_svc FROM order_role;
REVOKE ALL ON ALL TABLES IN SCHEMA order_svc FROM order_role;
REVOKE USAGE ON SCHEMA order_svc FROM order_role;
