apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ec-marketplace

resources:
  - namespace.yaml
  - gateway/
  - auth/
  - catalog/
  - inventory/
  - order/
  - search/
  - recommend/
  - notification/
  - inquiry/

commonLabels:
  app.kubernetes.io/part-of: ec-marketplace
