ALTER DEFAULT PRIVILEGES IN SCHEMA shipping_svc REVOKE ALL ON SEQUENCES FROM shipping_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA shipping_svc REVOKE ALL ON TABLES FROM shipping_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA shipping_svc FROM shipping_role;
REVOKE ALL ON ALL TABLES IN SCHEMA shipping_svc FROM shipping_role;
REVOKE USAGE ON SCHEMA shipping_svc FROM shipping_role;
