ALTER DEFAULT PRIVILEGES IN SCHEMA review_svc REVOKE ALL ON SEQUENCES FROM review_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA review_svc REVOKE ALL ON TABLES FROM review_role;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA review_svc FROM review_role;
REVOKE ALL ON ALL TABLES IN SCHEMA review_svc FROM review_role;
REVOKE USAGE ON SCHEMA review_svc FROM review_role;
